version: '3.7'

services:
  long-poll:
    ports:
      - "8000:8000"
    container_name: long-poll
    build:
      context: .
      dockerfile: Dockerfile.multi.scratch
    image: cybersamx/long-poll
    environment:
      - ENABLE_CLIENT=false
