version: '3.1'

services:
  mongo-server:
    image: mongo
    container_name: mongo-server
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: admin
    ports:
      - 27017:27017
    hostname: mongo
  mongo-cli:
    image: mongo
    stdin_open: true
    tty: true
    entrypoint:
      - mongo
      - --host
      - mongo-server
      - -u
      - root
      - -p
      - password
      - --authenticationDatabase
      - admin
      - admin
